GPT_01/gpt_01/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
]

GPT_01/gpt_01/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("list/", views.list, name="list"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
]

GPT_01/gpt_01/chatbot/urls.py
from django.urls import path
from . import views

app_name = "chatbot"

urlpatterns = [
    path("", views.chatbot_view, name="chatbot"),
]

GPT_01/gpt_01/gpt_01/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path("chatbot/", include("chatbot.urls")),
]

GPT_01/gpt_01/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

GPT_01/gpt_01/blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="post"
    )
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

GPT_01/gpt_01/chatbot/models.py
from django.db import models


class Chatbot(models.Model):

    question = models.CharField(max_length=200)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

GPT_01/gpt_01/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()

GPT_01/gpt_01/blog/forms.py
from django import forms
from .models import Post


class Postform(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        exclude = ("created_at", "updated_at", "author")

GPT_01/gpt_01/chatbot/forms.py
from django.db import models
from django import forms


from django import forms


class ChatForm(forms.Form):
    user_input = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "질문을 입력하세요...", "rows": 4, "cols": 50}
        ),
        label="질문",
    )

GPT_01/gpt_01/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
)
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm


# Create your views here.
@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('index')
        
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("index")


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("index")
    else:
        form = CustomUserCreationForm()

    context = {"form": form}
    return render(request, "accounts/signup.html", context)

GPT_01/gpt_01/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import Postform

# Create your views here.


def index(request):
    return render(request, "blog/index.html")


def list(request):
    posts = Post.objects.all()
    context = {"posts": posts}
    return render(request, "blog/list.html", context)


def create(request):
    if request.method == "POST":
        forms = Postform(request.POST)
        if forms.is_valid():
            post = forms.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("blog:detail", post.pk)
    else:
        forms = Postform()
    context = {"forms": forms}
    return render(request, "blog/create.html", context)


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    context = {"post": post}
    return render(request, "blog/detail.html", context)

GPT_01/gpt_01/chatbot/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .forms import ChatForm
import openai
from dotenv import load_dotenv
import os
from .models import Chatbot
from django.contrib.auth.decorators import login_required

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

prompt = "You are a competent nutritionist from Korea. Please be more concise. Numbered list format."


@login_required
def chatbot_view(request):
    form = ChatForm(request.POST or None)
    assistant_reply = None

    if request.method == "POST" and form.is_valid():
        user_input = form.cleaned_data["user_input"]

        messages = [{"role": "system", "content": prompt}]
        messages.append({"role": "user", "content": user_input})

        response = openai.ChatCompletion.create(model="gpt-4o-mini", messages=messages)
        assistant_reply = response.choices[0].message["content"]

        if request.user.is_authenticated:
            chat = Chatbot.objects.create(
                question=user_input,
                answer=assistant_reply,
            )
            chat.save()
    context = {"form": form, "assistant_reply": assistant_reply}
    return render(request, "chatbot/chatbot.html", context)

GPT_01/gpt_01/accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
    <h1>로그인</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인">
    </form>
{% endblock content %}

GPT_01/gpt_01/accounts/templates/accounts/signup.html
{% extends 'base.html' %}


{% block content %}
    
<h1>Signup</h1>

<form action="{% url 'accounts:signup' %}" method ='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>

{% endblock content %}
    

GPT_01/gpt_01/blog/templates/blog/create.html
{% extends 'base.html' %}

{% block content %}
<h1>글 작성</h1>
<a href="{% url 'blog:list' %}">목록으로</a>

<form action="{% url 'blog:create'  %}" method="POST">
    {% csrf_token %}
    {{ forms.as_p }}
    <input type="submit" value="작성">
</form>

{% endblock content %}

GPT_01/gpt_01/blog/templates/blog/detail.html
{% extends 'base.html' %}


{% block content %}
    
<h3>{{ post.title }}</h3>
<p>작성자 : {{ post.author }} </p>
<hr>

<p> {{ post.content }}</p>

작성일시 : {{ post.created_at }}
수정일시 : {{ post.updated_at }}
<hr>
<a href="{% url 'blog:list' %}"> 목록으로 </a>
{% endblock content %}
    

GPT_01/gpt_01/blog/templates/blog/index.html
{% extends 'base.html' %}


{% block content %}
    
<h1> 환영합니다 </h1>

<a href="{% url 'blog:list' %}">게시판</a>
<a href="{% url 'chatbot:chatbot' %}">챗봇</a>

{% endblock content %}
    

GPT_01/gpt_01/blog/templates/blog/list.html
{% extends 'base.html' %}

{% block content %}

<h1> 글 목록 </h1>
<a href="{% url 'blog:create' %}"> 새 글 작성 </a>


{% for post in posts %}
   <a href="{% url 'blog:detail' post.pk %}"> 
    <p>{{ post.title }} ({{ post.author }})</p> </a>
{% endfor %}
    


{% endblock content %}
    

GPT_01/gpt_01/chatbot/templates/chatbot/chatbot.html
{% extends 'base.html' %}

{% block content %}
    <h1>Chatbot</h1>
    
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">질문하기</button>
    </form>

    {% if assistant_reply %}
        <h3>대답:</h3>
        <p>{{ assistant_reply }}</p>
    {% endif %}
{% endblock %}

GPT_01/gpt_01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <div class = "navbar">
        <a href="{% url 'index' %}">홈</a>
        <a href="{% url 'chatbot:chatbot' %}">챗봇</a>
        <a href="{% url 'blog:list' %}">게시판</a>
        
        {% if request.user.is_authenticated %}
        <h3>Hello,{{ request.user.username }}</h3>

        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃">
        </form>
        {% else %}

        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>

        {% endif %}
            


    </div>

    {% block content %}
        
    {% endblock content %}

    <footer>
        <p>@cheachea's website. All Rights Reserved.</p>
    </footer>
        
</body>
</html>